# ref: https://www.elastic.co/guide/en/elasticsearch/reference/8.3/docker.html#_pulling_the_image
#
version: '2'
networks:
  bigdata:
    name: bigdata
services:
  es1:
    image: elasticsearch:8.2.3
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - bigdata
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 8G
    volumes:
      - ./es/es1:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.2.3
    ports:
      - 5601:5601
    networks:
      - bigdata
    depends_on:
      - es1
    volumes:
      - ./es/kibana:/usr/share/kibana/data
