version: '2'
networks:
  proxy-network:
    name: bigdata
services:
  CH:
    image: clickhouse/clickhouse-server
    networks:
      - proxy-network
    ports:
      - 19000:9000
      - 19100:9100
      - 8123:8123
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - /data/vols/ch-data:/var/lib/clickhouse
      - /data/vols/ch-log:/var/log/clickhouse-server
    ulimits:
      nofile: 262144
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 32G

