version: '2'
networks:
  proxy-network:
    name: bigdata
services:
  CH:
    image: clickhouse/clickhouse-server
    networks:
      - proxy-network
    ports:
      - 19000:9000
      - 19100:9100
      - 8123:8123
    volumes:
      #- /data/sonald/vols/ch-data:/var/lib/clickhouse
      #- /data/sonald/vols/ch-log:/var/log/clickhouse-server
      - ./config.xml:/etc/clickhouse-server/config.xml
    ulimits:
      nofile: 262144

