version: '2'
networks:
  proxy-network:
    name: bigdata
services:
  prom:
    image: prom/prometheus
    networks:
      - proxy-network
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

