global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prom'
    scrape_interval: 5s 
    static_configs:
      - targets: ['localhost:9090']
