FROM bde2020/spark-python-template:3.3.0-hadoop3.3

MAINTAINER Sian Cao <yinshuiboy@gmail.com>

ENV SPARK_MASTER_NAME spark-master
ENV SPARK_APPLICATION_PYTHON_LOCATION /app/spark.py
ENV SPARK_APPLICATION_ARGS "/app/spark.py"
