version: '2'
networks:
  bigdata:
    name: bigdata
services:
  spark-master:
    image: bitnami/spark:3.3
    volumes:
      - ./:/jobs
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - bigdata
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  spark-worker:
    image: bitnami/spark:3.3
    volumes:
      - ./:/jobs
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '3'
          memory: 8G
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8g
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - bigdata
