version: '2'
networks:
  proxy-network:
    external:
      name: bigdata
services:
  zk1:
    image: zookeeper
    networks:
      - proxy-network
    ports:
      - 2181:2181
    hostname: zk1
    volumes:
      - ./zk_data:/data
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk2:
    image: zookeeper
    networks:
      - proxy-network
    hostname: zk2
    volumes:
      - ./zk_data2:/data
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  zk3:
    image: zookeeper
    networks:
      - proxy-network
    hostname: zk3
    volumes:
      - ./zk_data3:/data
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181

  #kafka: 
    #image: ubuntu/kafka
    #ports:
      #- 9092:9092
    #depends_on:
      #- zk1
      #- zk2
      #- zk3
    #environment:
      #- ZOOKEEPER_HOST=zk1
    #volumes:
      #- ./kafka_data:/data

  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - proxy-network
    volumes:
      - ./kafka_data:/var/lib/kafka/data
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zk1
      - zk2
      - zk3

  kafka2:
    image: confluentinc/cp-kafka:latest
    networks:
      - proxy-network
    volumes:
      - ./kafka2_data:/var/lib/kafka/data
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zk1
      - zk2
      - zk3
